// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsPortalApp.EFContext;

#nullable disable

namespace StudentsPortalApp.Migrations
{
    [DbContext(typeof(StudentPortalDBContext))]
    partial class StudentPortalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentsPortalApp.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("StudentsPortalApp.Models.StudentCurriculamDetails", b =>
                {
                    b.Property<int>("StudentRollNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentRollNo"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("ComputerMarks")
                        .HasColumnType("int");

                    b.Property<int>("EnglishMarks")
                        .HasColumnType("int");

                    b.Property<int>("HindiMarks")
                        .HasColumnType("int");

                    b.Property<int>("MarathiMarks")
                        .HasColumnType("int");

                    b.Property<int>("MathsMarks")
                        .HasColumnType("int");

                    b.Property<int>("SSTMarks")
                        .HasColumnType("int");

                    b.Property<int>("ScienceMarks")
                        .HasColumnType("int");

                    b.HasKey("StudentRollNo");

                    b.ToTable("StudentCurriculamDetails");
                });

            modelBuilder.Entity("StudentsPortalApp.Models.StudentPersonalDetails", b =>
                {
                    b.Property<int>("RollNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RollNo"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollNo");

                    b.ToTable("StudentPersonalDetails");
                });

            modelBuilder.Entity("StudentsPortalApp.Models.StudentRecords", b =>
                {
                    b.Property<int>("RollNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RollNo"));

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollNo");

                    b.ToTable("StudentRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
